import { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from 'styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>react-query basics</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='https://react-query.tanstack.com/'>react-query</a> basics
        </h1>

        <p className={styles.description}>Contents:</p>

        <div className={styles.grid} style={{ cursor: 'pointer' }}>
          <Link href='./person/1'>
            <div className={styles.card}>
              <h2>useQuery &rarr;</h2>
              <p>
                Fetch using <code className={styles.code}>useQuery</code>.
              </p>
            </div>
          </Link>
        </div>
      </main>
    </div>
  )
}

export default Home
